import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AsideBar from '@/components/asidebar'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-full`}>

        <Navbar />

        <main className="w-full max-w-7xl border-b h-full mx-auto mb-20 flex gap-8  justify-between px-5 sm:px-6 py-5 lg:px-8 flex mt-10">
          <AsideBar/>
          {children}
        </main>

        <footer className="py-6 md:px-8 md:py-0"><div className="container flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row"><p className="text-balance text-center text-sm leading-loose text-muted-foreground md:text-left">Built by <a href="https://twitter.com/shadcn" target="_blank" rel="noreferrer" className="font-medium underline underline-offset-4">shadcn</a>. The source code is available on <a href="https://github.com/shadcn-ui/ui" target="_blank" rel="noreferrer" className="font-medium underline underline-offset-4">GitHub</a>.</p></div></footer>
      
      </body>
    </html>
  );
}

{/*<main className="w-full max-w-7xl mx-auto items-center justify-between px-5 sm:px-6 py-5 lg:px-8 flex mt-3">{children}</main>*/}
