import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AsideBar from '@/components/asidebar'
import Footer from "@/components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full h-full`}>

        <Navbar />

        <main className="w-full max-w-7xl border-b h-full mx-auto mb-10 flex gap-8  justify-between px-5 sm:px-6 py-5 lg:px-8 flex mt-10">
          <AsideBar/>
          {children}
        </main>

        <Footer />

      </body>
    </html>
  );
}

{/*<main className="w-full max-w-7xl mx-auto items-center justify-between px-5 sm:px-6 py-5 lg:px-8 flex mt-3">{children}</main>*/}
